// Server generated by Zap v0.6.1 (https://github.com/red-blox/zap)
export const Replication: {
	fire: (player: Player, value?: unknown) => void
	fireAll: (value?: unknown) => void
	fireExcept: (except: Player, value?: unknown) => void
	fireList: (list: Player[], value?: unknown) => void
};
export const ConfirmLoaded: {
	on: (callback: (player: Player) => void) => void
};
