# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
wally = "upliftgames/wally@0.3.1"
rojo = "rojo-rbx/rojo@7.3.0"
remodel = "rojo-rbx/remodel@0.11.0"
lune = "filiptibell/lune@0.7.9"
# rojo = "rojo-rbx/rojo@6.2.0"