// Client generated by Zap v0.6.1 (https://github.com/red-blox/zap)
export const ConfirmLoaded: {
	fire: () => void;
};
export const Replication: {
	on: (callback: (value?: unknown) => void) => void;
};
